let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Gripex",
    price: 15,
    desc: "multi-ingredient drug with clearing effects.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Panadol",
    price: 10,
    desc: "contain a disintegrant system .",
    img: "images/img-2.png",
  },
  {
    id: "wuefbncxbsn",
    name: "Novex",
    price: 25,
    desc: "provide high-resolution analysis of digests.",
    img: "images/img-3.png",
  },
  {
    id: "thyfhcbcv",
    name: "Fervex",
    price: 30,
    desc: "contain a disintegrant system .",
    img: "images/img-4.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Saifoxyl",
    price: 23,
    desc: " Amoxicilline trihydratée par gélule sous forme anhydre.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Plantex",
    price: 22,
    desc: "effective and environmentally friendly weed control.",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "BioGrip",
    price: 50,
    desc: "a universal Mineral Primer for Interior/Exterior use.",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Gripe Water",
    price: 45,
    desc: "a mixture of water, baking soda, and herbs.",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Triplex",
    price: 85,
    desc: " identical to a duplex, except that it has three units.",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Oscillococcinum",
    price: 40,
    desc: "reduces the duration of flu-like symptoms",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Cyclodex",
    price: 35,
    desc: "indicated for the symptomatic treatment.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Alezine",
    price: 5,
    desc: "ALEZINE 5 mg Comprimé orodispersible.",
    img: "images/img-12.png",
  },
];
